# Generated by Django 3.0 on 2019-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='added',
        ),
        migrations.AddField(
            model_name='profile',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='profile',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
